include:
  - apps/astro-stream/docker-compose.yaml
  - apps/static/docker-compose.yaml
services:
  app:
    image: jc21/nginx-proxy-manager
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 81:81

    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./data:/data
networks:
  default:
    name: nginx