services:
  server:
    image: docker.gitea.com/gitea:1.25.3
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__actions__ENABLED=true
    restart: always
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3003:3000"
      - "222:22"
    networks:
      - nginx

  runner:
    image: docker.io/gitea/act_runner:latest
    container_name: gitea_runner
    restart: always
    depends_on:
      - server
    environment:
      - CONFIG_FILE=/config.yaml
      - GITEA_INSTANCE_URL=http://gitea:3000
      - GITEA_RUNNER_REGISTRATION_TOKEN=...
      - GITEA_RUNNER_NAME=docker_runner
      - GITEA_RUNNER_LABELS=ubuntu-latest:docker://node:24-bookworm
    volumes:
      - ./config.yaml:/config.yaml:ro
      - ./gitea-runner:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - nginx

networks:
  nginx:
    external: true
